---
name: Manual Apply TG to AWS
on:
  workflow_dispatch:
    inputs:
      folder:
        description: "Folder to run Terragrunt"
        required: true
        default: "."
env:
  AWS_REGION: us-east-1

  TERRAFORM_VERSION: "1.3.7"
  TERRAGRUNT_VERSION: "0.42.5"
jobs:
  manual-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: "[AWS] Configure credentials"
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: "[Setup] Terraform"
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ env.TERRAFORM_VERSION }}

      - name: "[Setup] Terragrunt"
        uses: autero1/action-terragrunt@v1.1.0
        with:
          terragrunt_version: ${{ env.TERRAGRUNT_VERSION }}

      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: read users
        id: users
        run: |
          echo 'USERS<<EOF' >> $GITHUB_OUTPUT
          cat ./owners.json >> $GITHUB_OUTPUT
          echo '\n' >> $GITHUB_OUTPUT
          echo 'EOF' >> $GITHUB_OUTPUT
      - name: check user in list
        if: ${{ !contains(fromJson(steps.users.outputs.USERS), github.actor) }}
        run: |
          echo "::error::user ${{ github.actor }} not found in approved list"
          exit 1
      - name: Terraform Apply
        working-directory: "${{ github.event.inputs.folder }}"
        run: terragrunt run-all apply --terragrunt-non-interactive
